# Generated by Django 3.1.4 on 2020-12-03 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('sobrenome', models.CharField(max_length=32)),
                ('telefone', models.CharField(max_length=16)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Universidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Virtual.instituicao')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Virtual.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Mobilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_para', models.CharField(choices=[('D', 'de'), ('P', 'para')], max_length=1)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Virtual.pessoa')),
                ('universidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Virtual.universidade')),
            ],
        ),
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Virtual.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField()),
                ('mobilidade', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Virtual.mobilidade')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Virtual.pessoa')),
            ],
        ),
    ]
