# Generated by Django 3.1.4 on 2020-12-04 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Virtual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilidade',
            name='periodo_fim',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='mobilidade',
            name='periodo_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
