# Generated by Django 3.1.4 on 2020-12-04 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Virtual', '0003_auto_20201204_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
